#!/usr/bin/env python3
"""
Above Kitch — Weekly Intake Writer
Writes a structured intake.json for the given week based on questionnaire answers.

Called by Claude after asking Austin the 6 intake questions, passing answers as JSON.

Usage:
    python run_weekly_intake.py 2026-05-11 '{...intake JSON...}'
    python run_weekly_intake.py 2026-05-11  # interactive CLI mode

The intake.json is saved to:
    weekly/{week_date}/intake.json

See references/intake_schema.md for full documentation.
"""

import os
import sys
import json
from datetime import datetime, timedelta

# ─── DEFAULTS ────────────────────────────────────────────────────────────────

DEFAULTS = {
    "eat_out_nights": [],
    "last_week_feedback": {
        "repeat": [],
        "avoid": [],
        "notes": "",
    },
    "cravings": "",
    "protein_rotation": {
        "increase": [],
        "reduce": [],
    },
    "prep_availability": "full",
    "cameron_notes": "",
    "calendar_eat_out_nights": [],
}

DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
PROTEINS = ["chicken", "salmon", "shrimp", "ground_turkey", "ground_beef", "steak", "lamb", "pork", "eggs"]
PREP_OPTIONS = ["full", "short", "minimal", "none"]


# ─── BUILDERS ─────────────────────────────────────────────────────────────────

def build_intake(week_date, answers: dict, generated_by="questionnaire") -> dict:
    """
    Merge user answers over defaults and return a complete intake dict.
    The `answers` dict can contain any subset of intake fields.
    Missing fields fall back to DEFAULTS.
    """
    intake = {
        "week_date": week_date,
        "completed_at": datetime.now().isoformat(timespec="seconds"),
        "generated_by": generated_by,
    }

    # Merge each field from answers, falling back to defaults
    for key, default in DEFAULTS.items():
        if key in answers:
            val = answers[key]
            # Validate day names in eat_out_nights
            if key == "eat_out_nights":
                val = [d.capitalize() for d in val if d.capitalize() in DAYS]
            # Validate prep_availability
            if key == "prep_availability" and val not in PREP_OPTIONS:
                print(f"  ⚠ Invalid prep_availability '{val}' — defaulting to 'full'")
                val = "full"
            # Validate protein lists
            if key == "protein_rotation":
                val = {
                    "increase": [p for p in val.get("increase", []) if p in PROTEINS],
                    "reduce":   [p for p in val.get("reduce", [])   if p in PROTEINS],
                }
            intake[key] = val
        else:
            import copy
            intake[key] = copy.deepcopy(default)

    return intake


def write_intake(week_date: str, intake: dict) -> str:
    """Write intake dict to weekly/{week_date}/intake.json. Returns the file path."""
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    week_dir    = os.path.join(project_dir, "weekly", week_date)

    os.makedirs(week_dir, exist_ok=True)
    intake_path = os.path.join(week_dir, "intake.json")

    with open(intake_path, "w") as f:
        json.dump(intake, f, indent=2)

    return intake_path


def load_intake(week_date: str) -> dict | None:
    """
    Load intake.json for the given week. Returns None if it doesn't exist.
    Used by generate_meal_plan_pdf.py to check for existing intake.
    """
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    intake_path = os.path.join(project_dir, "weekly", week_date, "intake.json")

    if not os.path.exists(intake_path):
        return None

    with open(intake_path) as f:
        return json.load(f)


def summarize_intake(intake: dict) -> str:
    """Return a human-readable summary of the intake for logging."""
    lines = ["── Weekly Intake Summary ──"]
    lines.append(f"  Week:          {intake['week_date']}")
    lines.append(f"  Generated by:  {intake.get('generated_by', 'unknown')}")
    lines.append(f"  Completed at:  {intake.get('completed_at', 'unknown')}")

    eat_out = intake.get("eat_out_nights", [])
    cal_out = intake.get("calendar_eat_out_nights", [])
    all_out = sorted(set(eat_out + cal_out), key=lambda d: DAYS.index(d) if d in DAYS else 99)
    if all_out:
        lines.append(f"  Eating out:    {', '.join(all_out)}")
    else:
        lines.append("  Eating out:    None — all 7 dinners home-cooked")

    prep = intake.get("prep_availability", "full")
    prep_labels = {"full": "Full session (2+ hrs, smoker OK)", "short": "Short (60–90 min)",
                   "minimal": "Minimal (under 45 min)", "none": "No Sunday prep"}
    lines.append(f"  Sunday prep:   {prep_labels.get(prep, prep)}")

    fb = intake.get("last_week_feedback", {})
    if fb.get("repeat"):
        lines.append(f"  Repeat:        {', '.join(fb['repeat'])}")
    if fb.get("avoid"):
        lines.append(f"  Avoid:         {', '.join(fb['avoid'])}")
    if fb.get("notes"):
        lines.append(f"  Feedback:      {fb['notes']}")

    if intake.get("cravings"):
        lines.append(f"  Cravings:      {intake['cravings']}")

    pr = intake.get("protein_rotation", {})
    if pr.get("increase"):
        lines.append(f"  More of:       {', '.join(pr['increase'])}")
    if pr.get("reduce"):
        lines.append(f"  Less of:       {', '.join(pr['reduce'])}")

    if intake.get("cameron_notes"):
        lines.append(f"  Cameron:       {intake['cameron_notes']}")

    return "\n".join(lines)


# ─── INTERACTIVE CLI ──────────────────────────────────────────────────────────

def ask(prompt, default=None):
    """Ask a question and return the answer. Empty input → default."""
    suffix = f" [{default}]" if default else " (skip → default)"
    try:
        val = input(f"\n{prompt}{suffix}\n> ").strip()
    except (EOFError, KeyboardInterrupt):
        val = ""
    return val if val else default


def interactive_questionnaire(week_date: str) -> dict:
    """Run the 6-question interactive CLI questionnaire. Returns answers dict."""
    week_dt = datetime.strptime(week_date, "%Y-%m-%d")
    week_end = (week_dt + timedelta(days=6)).strftime("%B %-d")
    print(f"\n{'='*60}")
    print(f"ABOVE KITCH — Weekly Intake Questionnaire")
    print(f"Week of {week_dt.strftime('%B %-d')}–{week_end}")
    print(f"{'='*60}")
    print("Answer 6 quick questions. Press Enter to skip any question and use the default.\n")

    answers = {}

    # Q1 — Eat-out nights
    raw = ask(
        "Q1/6 — Which nights are you eating out or skipping dinner?\n"
        "  Enter day names separated by commas (e.g. Wednesday, Friday)",
        default=""
    )
    answers["eat_out_nights"] = [d.strip().capitalize() for d in raw.split(",") if d.strip()] if raw else []

    # Q2 — Last week feedback
    print("\nQ2/6 — Last week feedback:")
    raw_repeat = ask("  Which recipes would you repeat? (recipe IDs or names, comma-separated)", default="")
    raw_avoid  = ask("  Anything to avoid for a few weeks?", default="")
    raw_notes  = ask("  Any other feedback on last week?", default="")
    answers["last_week_feedback"] = {
        "repeat": [r.strip() for r in raw_repeat.split(",") if r.strip()] if raw_repeat else [],
        "avoid":  [r.strip() for r in raw_avoid.split(",")  if r.strip()] if raw_avoid  else [],
        "notes":  raw_notes or "",
    }

    # Q3 — Cravings
    raw = ask("Q3/6 — Any cravings this week? (cuisine, ingredient, vibe — anything goes)", default="")
    answers["cravings"] = raw or ""

    # Q4 — Protein rotation
    print(f"\nQ4/6 — Protein rotation. Options: {', '.join(PROTEINS)}")
    raw_more = ask("  More of? (comma-separated)", default="")
    raw_less = ask("  Less of? (comma-separated)", default="")
    answers["protein_rotation"] = {
        "increase": [p.strip() for p in raw_more.split(",") if p.strip()] if raw_more else [],
        "reduce":   [p.strip() for p in raw_less.split(",") if p.strip()] if raw_less else [],
    }

    # Q5 — Prep availability
    raw = ask(
        "Q5/6 — Sunday batch prep availability?\n"
        "  Options: full (2+ hrs), short (60–90 min), minimal (<45 min), none",
        default="full"
    )
    answers["prep_availability"] = raw.lower() if raw.lower() in PREP_OPTIONS else "full"

    # Q6 — Cameron notes
    raw = ask("Q6/6 — Any updates for Cameron this week?", default="")
    answers["cameron_notes"] = raw or ""

    return answers


# ─── MAIN ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Usage:
        # Questionnaire answers only
        python run_weekly_intake.py 2026-05-11 '{...answers json...}'

        # Questionnaire answers + calendar analysis results
        python run_weekly_intake.py 2026-05-11 '{...answers json...}' '{...calendar_analysis json...}'

        # Interactive CLI (no args except week_date)
        python run_weekly_intake.py 2026-05-11

    The calendar_analysis JSON is the output from analyze_calendar.py:
        {
          "confirmed_eat_out": ["Wednesday"],
          "evening_conflicts": [{"day": "Wednesday", "summary": "Pickup Soccer", ...}],
          "travel_days": []
        }
    """
    if len(sys.argv) < 2:
        print("Usage: python run_weekly_intake.py <week_date> ['{...answers...}'] ['{...calendar...}']")
        print("       python run_weekly_intake.py 2026-05-11")
        sys.exit(1)

    week_date = sys.argv[1]

    # Validate date format
    try:
        datetime.strptime(week_date, "%Y-%m-%d")
    except ValueError:
        print(f"Error: week_date must be YYYY-MM-DD, got '{week_date}'")
        sys.exit(1)

    # Parse questionnaire answers
    if len(sys.argv) >= 3:
        try:
            answers = json.loads(sys.argv[2])
            generated_by = "questionnaire"
        except json.JSONDecodeError as e:
            print(f"Error parsing JSON answers: {e}")
            sys.exit(1)
    else:
        answers = interactive_questionnaire(week_date)
        generated_by = "questionnaire"

    # Parse optional calendar analysis
    calendar_analysis = {}
    if len(sys.argv) >= 4:
        try:
            calendar_analysis = json.loads(sys.argv[3])
            generated_by = "questionnaire+calendar"
        except json.JSONDecodeError as e:
            print(f"Warning: could not parse calendar analysis JSON: {e}", file=sys.stderr)

    # Merge calendar-detected nights into answers
    if calendar_analysis:
        cal_eat_out     = calendar_analysis.get("confirmed_eat_out", [])
        cal_conflicts   = calendar_analysis.get("evening_conflicts", [])
        travel_days_raw = calendar_analysis.get("travel_days", [])
        travel_days     = [t["day"] for t in travel_days_raw] if travel_days_raw else []

        # calendar_eat_out_nights = confirmed eat-out + travel days
        answers["calendar_eat_out_nights"] = sorted(
            set(cal_eat_out + travel_days),
            key=lambda d: DAYS.index(d) if d in DAYS else 99
        )
        # Store conflict details as additional context
        if cal_conflicts:
            answers.setdefault("calendar_conflicts", [])
            answers["calendar_conflicts"] = cal_conflicts
    else:
        answers.setdefault("calendar_eat_out_nights", [])

    intake = build_intake(week_date, answers, generated_by=generated_by)

    # Patch calendar_eat_out_nights into intake directly (it's not in DEFAULTS)
    if "calendar_eat_out_nights" in answers:
        intake["calendar_eat_out_nights"] = answers["calendar_eat_out_nights"]
    if "calendar_conflicts" in answers:
        intake["calendar_conflicts"] = answers["calendar_conflicts"]

    path = write_intake(week_date, intake)
    print(f"\n✓ Intake saved: {path}")
    print(summarize_intake(intake))
